---
- name: Create message filter pacakge directory on brokers
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    mode: "{{ file_permission_mode }}"
  with_items:
    - "{{ tgt_msg_filter_package_dir }}"

- name: Check if the message filter package already exists
  stat:
    path: "{{ tgt_msg_filter_package_dir }}/{{ msg_filter_package_name }}"
  register: msg_filter_pkg_stat

- name: Check if the message filter packate already exists on the target host. If not, copy it from local host when 'internet_download' is false
  copy:
    src: "{{ local_bin_homedir }}/{{ msg_filter_package_name }}"
    dest: "{{ tgt_msg_filter_package_dir }}/{{ msg_filter_package_name }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
  when: not msg_filter_pkg_stat.stat.exists and not internet_download|bool

- name: Check if the message filter packate already exists on the target host. If not, Download Pulsar from internet when 'internet_download' is true 
  get_url:
    url: "{{ msg_filter_pkg_download_url }}"
    dest: "{{ tgt_msg_filter_package_dir }}/{{ msg_filter_package_name }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
  when: not msg_filter_pkg_stat.stat.exists and internet_download|bool