---
#
# Collect and get server gclog files
# -------------------------------------------
#
- name: "[{{ srv_component }}] Copy Gclog file to the temporary remote folder (to avoid checksum mismatch error)"
  copy:
    src: "{{ tgt_pulsar_gc_log_homedir }}/{{ gclog_filename }}"
    dest: "{{ tgt_collected_srvfiles_homedir }}/{{ srv_component }}/{{ gclog_filename }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    remote_src: true

- name: "[{{ srv_component }}] Copy Gclog file to local"
  fetch:
    src: "{{ tgt_collected_srvfiles_homedir }}/{{ srv_component }}/{{ gclog_filename }}"
    dest: "{{ local_collected_srvfiles_homedir }}/{{ bkup_subfolder }}/gclog/{{ srv_component }}/{{ inventory_hostname }}/"
    flat: yes