---
- name: Check if Pulsar broker is already running
  stat:
    path: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-broker.pid"
  register: stat_result

- name: Start Pulsar broker, if it is not running yet
  become: true
  become_method: sudo
  become_user: "{{ pulsar_user }}"
  shell: "{{ broker_jvm_options|trim }} {{ tgt_pulsar_inst_dir }}/bin/pulsar-daemon start broker"
  when: not stat_result.stat.exists

- name: Wait until broker service non-TLS port and web service non-TLS port are ready
  wait_for:
    host: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}"
    port: "{{ item }}"
    delay: 2
    timeout: 120
  with_items:
    - "{{ broker_svc_port }}"
    - "{{ web_svc_port }}"