---
- name: Check if AdminConsole is already running (listening on port 6454)
  wait_for:
    host: "{{ private_ip }}"
    port: "{{ ac_listen_port }}"
    delay: 5
    timeout: 10
    msg: "Timeout waiting for port {{ ac_listen_port }} to respond"
  register: ac_port_check
  ignore_errors: yes

- name: Start AdminConsole if it is not running yet
  become: true
  become_method: sudo
  ## NOTE: Do NOT use Ansible "become_user"! Otherwise, ansible will fail to write .async file under /home/{{ pulsar_user }}
  # become_user: "{{ pulsar_user }}"
  shell: "cd {{ tgt_adminConsole_inst_dir }}/server/; nohup sudo -u {{ pulsar_user }} npm start 2>&1 &"
  # Async shell execution with a very large number
  async: 3153600000 # 100 years
  register: ac_startSVC_cmdcat
  when: ac_port_check.failed == true
- debug: msg="ac_startSVC_cmdcat - {{ ac_startSVC_cmdcat }}"
  when: show_debug_msg|bool 