---
- name: Copy Pulsar AdminConsole dashboard config (config.js) template
  template:
    src: templates/ac_config.js.tmp
    dest: "{{ tgt_adminConsole_inst_dir }}/dashboard/dist/config.js"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    mode: "{{ file_permission_mode_noexec }}"

- name: Replace Pulsar AdminConsole config setting placeholders with cluster specific information
  replace:
      path: "{{ tgt_adminConsole_inst_dir }}/dashboard/dist/config.js"
      regexp: "{{ item.regexp }}"
      replace: "{{ item.line }}"
  with_items:
    - { regexp: '{{ placeHolder_homeCluster }}', line: "{{ cluster_name }}" }
    - { regexp: '{{ placeHolder_apiVersion }}', line: "{{ pulsarLS_ver_main }}" }
    - { regexp: '{{ placeHolder_brokerSvcUrl }}', line: "{% if enable_brkr_tls is defined and enable_brkr_tls|bool %}pulsar+ssl://{{ brokerSvcTlsListStr }}{% else %}pulsar://{{ brokerSvcListStr }}{% endif %}" }
    # - { regexp: '{{ placeHolder_webSvcUrl }}', line: "{% if enable_brkr_tls is defined and enable_brkr_tls|bool %}https://{{ webSvcTlsListStr }}{% else %}http://{{ webSvcListStr }}{% endif %}" }
    - { regexp: '{{ placeHolder_adminTokenPath }}', line: "{% if enable_brkr_authNR is defined and enable_brkr_authNR|bool %}file://{{ tgt_adminConsole_sec_dir }}/jwt/token/{{ super_user_roles[0] }}.jwt{% else %}\"\"{% endif %}" }
    - { regexp: '{{ placeHolder_caCertificate }}', line: "{% if enable_brkr_tls is defined and enable_brkr_tls|bool %}{{ tgt_adminConsole_sec_dir }}/tls/rootca/{{ public_cacert_name }}{% else %}\"\"{% endif %}" }
    
- name: Copy Nginx Web Server config (nginx.conf) template
  template:
    src: templates/ac_nginx.conf.tmp
    dest: "/etc/nginx/nginx.conf"
    mode: "{{ file_permission_mode_noexec }}"

- name: Replace Nginx config setting placeholders with cluster specific information
  replace:
      path: "/etc/nginx/nginx.conf"
      regexp: "{{ item.regexp }}"
      replace: "{{ item.line }}"
  with_items:
    - { regexp: '{{ placeHolder_homeCluster }}', line: "{{ cluster_name }}" }
    - { regexp: '{{ placeHolder_brkrWebPortList }}', line: "{% if enable_brkr_tls is defined and enable_brkr_tls|bool %}{{ brkrWebTLSArrStrVar }}{% else %}{{ brkrWebArrStrVar }}{% endif %}" }
    - { regexp: '{{ placeHolder_acListenHost }}', line: "{{ private_ip }}" }
    - { regexp: '{{ placeHolder_acListenPort }}', line: "{{ ac_listen_port }}" }
    - { regexp: '{{ placeHolder_nginxListenPort }}', line: "{{ nginx_listen_port }}" }
    - { regexp: '{{ placeHolder_nginxStatusPort }}', line: "{{ nginx_status_port }}" }