---
# When restoring from the backup, we need to restore from a specific subfolder
#   that corresponds to the operation that created the backup files
- name: Copy Pulsar config files and related security files to the backup folder
  copy:
    remote_src: yes
    src: "{{ tgt_pulsar_conf_bkup_homedir }}/{{ bkup_subfolder_name }}/{{ item }}"
    dest: "{{ tgt_pulsar_inst_dir }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    # overwrite existing config files with the ones from the backup location
    force: yes
  with_items:
    - conf
    - security