---
# Ubuntu/APT installation
- name: Get the current nodejs server version if it is already installed
  shell:
    cmd: "node -v 2>&1"
  ignore_errors: yes
  register: "_nodejs_ver"
- debug: msg="{{ _nodejs_ver.stdout }}"
  when: show_debug_msg|bool

- name: Check whether or not we need to install a newer version nodejs
  set_fact:
    install_nodejs: "{{ force_nodejs_install|bool or _nodejs_ver.rc|int != 0 or _nodejs_ver.stdout.split('v')[1] is version(tgt_nodejs_ver, '<') }}"
- debug: msg="{{ install_nodejs }}"
  when: show_debug_msg|bool

- name: Download Node.js setup script
  get_url: 
    url: "https://deb.nodesource.com/setup_{{ tgt_nodejs_ver_major }}.x"
    dest: /tmp/setup_nodejs_{{ tgt_nodejs_ver_major }}
    mode: "0755"
  when: install_nodejs|bool

- name: Setup Node.js
  command: /tmp/setup_nodejs_{{ tgt_nodejs_ver_major }}
  when: install_nodejs|bool

- name: Install nodejs   
  apt: 
    name: "nodejs={{ tgt_nodejs_ver }}-1nodesource1"
    update_cache: yes
    state: present
  when: install_nodejs|bool