---
- name: Check if Pulsar binary already exists
  stat:
    path: "{{ tgt_pkg_pular_dir }}/{{ pulsarLS_bin_name }}"
  register: pulsar_distro_stat
# - debug: msg="{{pulsar_distro_stat.stat.exists }}, {{ internet_download }}"
#   when: show_debug_msg|bool

- name: Check if the target Pulsar binary exists on the target host yet. If not, copy it from local host when 'internet_download' is false
  copy:
    src: "{{ local_bin_homedir }}/{{ pulsarLS_bin_name }}"
    dest: "{{ tgt_pkg_pular_dir }}/{{ pulsarLS_bin_name }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
  when: not pulsar_distro_stat.stat.exists and not internet_download|bool

- name: Check if the Pulsar binary exists on the target host yet. If not, Download Pulsar from internet when 'internet_download' is true 
  get_url:
    url: "{{ pulsarLS_bin_download_url }}"
    dest: "{{ tgt_pkg_pular_dir }}/{{ pulsarLS_bin_name }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
  when: not pulsar_distro_stat.stat.exists and internet_download|bool