---
- name: Start HeartBeat if it is not running yet
  ## NOTE: Do NOT use Ansible "become_user"! Otherwise, ansible will fail to write .async file under /home/{{ pulsar_user }}
  # become_user: "{{ pulsar_user }}"
  shell: cd {{ tgt_heartBeat_inst_dir }}; export PULSAR_OPS_MONITOR_CFG=./runtime.yaml; nohup ./{{ heartBeat_bin_name.split('.gz')[0] }} >/dev/null 2>&1 &
#  shell: "cd {{ tgt_adminConsole_inst_dir }}/server/; export NODE_EXTRA_CA_CERTS={% if enable_brkr_tls is defined and enable_brkr_tls|bool %}{{ tgt_adminConsole_sec_dir }}/tls/rootca/{{ public_cacert_name }}{% else %}  {% endif %}; nohup npm start 2>&1 &"
  # Async shell execution with a very large number
  async: 3153600000 # 100 years
  register: hb_startSvc_cmdcat
  when: not srvStarted|trim|bool
- debug: msg="hb_startSvc_cmdcat.failed - {{ hb_startSvc_cmdcat.failed }}"
  when: show_debug_msg|bool and not srvStarted|trim|bool

- name: Wait until HeartBeat is ready
  wait_for:
    host: "{{ private_ip }}"
    port: "{{ ac_listen_port }}"
    delay: 2
    timeout: 120
  when: not srvStarted|trim|bool