---
- name: Start HeartBeat if it is not running yet
  ## NOTE: Do NOT use Ansible "become_user"! Otherwise, ansible will fail to write .async file under /home/{{ pulsar_user }}
  # become_user: "{{ pulsar_user }}"
  # Also, export GOPS_CONFIG_DIR=... is requirement to redirect GOLANG GOPS output 
  shell: cd {{ tgt_heartBeat_inst_dir }}; {% if sudo_needed|bool %}sudo -u {{ pulsar_user }} {% endif %} -- bash -c 'cd {{ tgt_heartBeat_inst_dir }}; export PULSAR_OPS_MONITOR_CFG=./runtime.yaml; export GOPS_CONFIG_DIR={{ hb_gops_tempdir }}; nohup ./{{ heartBeat_bin_name.split('.gz')[0] }} >/dev/null 2>&1 &'
  # Async shell execution with a very large number
  async: 3153600000 # 100 years
  register: hb_startSvc_cmdcat
  when: not srvStarted|trim|bool
- debug: msg="hb_startSvc_cmdcat.failed - {{ hb_startSvc_cmdcat.failed }}"
  when: show_debug_msg|bool and not srvStarted|trim|bool

- name: Wait until HeartBeat is ready
  wait_for:
    host: "{{ private_ip }}"
    port: "{{ hb_listen_port }}"
    delay: 2
    timeout: 120
  when: not srvStarted|trim|bool