---
##
##  NOTE: DO not change the sequence of the tasks!
##        Make sure "02.deploy_pulsarCluster.yaml" playbook has been executed beforehand!
##

#########################
# NOTE: This step must be executed after "pulsarClient" has been propery configured. 
#       Otherwise, "pulsar-admin" connection will be directed to localhost and therefore causes connection failure
- hosts: bookkeeper
  any_errors_fatal: true
  become: "{{ sudo_needed }}"
  become_method: sudo
  roles: 
    - { role: pulsar/bookkeeper/_pre_bkieRackMinNumCheck, 
        run_once: true,
        when: config_rackAwareness is defined and config_rackAwareness|bool }
    - { role: pulsar/bookkeeper/bkie_assignRack, 
        when: config_rackAwareness is defined and config_rackAwareness|bool }