---
##
##  NOTE: DO not change the sequence of the tasks!
##        Make sure "02.deploy_pulsarCluster.yaml" playbook has been executed beforehand!
##

#########################
# PreWork
# -----------------------
# - Get broker list in deseried formats and save them in variables
#   They are needed in later steps for Pulsar configurations
- hosts: broker
  gather_facts: true
  run_once: true
  roles:
    - { role: pulsar/broker/_pre_brokerListVar }


#########################
# AdminConsole Related
# -----------------------
# - AdminConsole node.js server
- hosts: adminConsole
  become: "{{ sudo_needed }}"
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true
  vars:
    srvStarted: true
  roles:
    - { role: misc/_inst_njs }
    - { role: adminconsole/ac_instBinary }
    - { role: adminconsole/ac_configAc }
    # Check the current status of the AdminConsole application server
    - { role: misc/_check_svc_status,
        srv_component: 'adminConsole',
        srv_ports: ["{{ ac_listen_port }}"] }
    # Start the AdminConsole application server
    - { role: adminconsole/ac_startAcSvc }
