---
##
##  NOTE: DO not change the sequence of the tasks!
##        Make sure "02.deploy_pulsarCluster.yaml" playbook has been executed beforehand!
##

#########################
# PreWork
# -----------------------
- hosts: pulsarClient
  any_errors_fatal: true
  become: "{{ sudo_needed }}"
  become_method: sudo
  roles: 
    # Set global variables to be used in other tasks/roles
    - { role: pulsar/common/pulsar_setGlobalVars, varList: 'all' }

#########################
# HeartBeat Related
# -----------------------
- hosts: heartBeat
  become: "{{ sudo_needed }}"
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true
  vars:
    srvStarted: true
    srv_component: 'heartBeat'
    srv_ports: ["{{ hb_listen_port }}"]
  roles: 
    - { role: heartbeat/hb_instBinary }
    - { role: heartbeat/hb_config }
    # Check the current status of the AdminConsole application server
    - { role: misc/_check_svc_status }
    # Start the HeartBeat application server
    - { role: heartbeat/hb_startHbSvc }    
