---
##
##  NOTE: DO not change the sequence of the tasks!
##        Make sure "02.deploy_pulsarCluster.yaml" playbook has been executed beforehand!
##

#########################
# HeartBeat Related
# -----------------------
- hosts: heartBeat
  become: "{{ sudo_needed }}"
  become_method: sudo
  any_errors_fatal: true
  roles: 
    - { role: heartbeat/hb_instBinary }
    - { role: heartbeat/hb_config }
  post_tasks:
    - name: Start Pulsar HeartBeat
      shell: cd {{ tgt_heartBeat_inst_dir }}; nohup PULSAR_OPS_MONITOR_CFG=./run_time.yaml {{ heartBeat_bin_name.split('.gz')[0] }} 2>&1 &