---
#########################
# PreWork
# -----------------------
# - Get broker list in deseried formats and save them in variables
#   They are needed in later steps for Pulsar configurations
- hosts: pulsarServer
  gather_facts: true
  run_once: true
  roles: 
    - { role: pulsar/common/_pre_brokerListVar }
    - { role: pulsar/common/_pre_brokerNginxArrStrVar }


#########################
# AdminConsole Related
# -----------------------
# - 
- hosts: adminConsole
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true
  roles: 
    - { role: misc/_inst_njs }
    - { role: misc/_inst_nginx }
    - { role: adminconsole/ac_instBinary }
    - { role: adminconsole/ac_config }
    - { role: adminconsole/ac_startAcSvc }
    - { role: adminconsole/ac_startNginxSvc }