---
# Restart dedicated function brokers, one by one, if relevant
- hosts: functions_worker
  any_errors_fatal: true
  become: "{{ sudo_needed }}"
  become_method: sudo
  serial: 1
  vars:
    srvStarted: true
    srv_component: 'functions_worker'
    srv_ports: [
      "{% if enable_fwrkr_tls|bool %}{{ funcs_worker_port_tls }}{% else %}{{ funcs_worker_port }}{% endif %}"
    ]
  roles:
    # Check the current status of function workers
    - { role: misc/_check_svc_status,
        when: deploy_functions_worker is defined and deploy_functions_worker == 'dedicated' }
    # Stop function workers
    - { role: pulsar/common/pulsar_stopSvc, srvStarted: true, 
        when: deploy_functions_worker is defined and deploy_functions_worker == 'dedicated' }
    # Start function workers
    - { role: pulsar/common/pulsar_startSvc,  
        srvStarted: false, 
        srv_options: "{{ funcs_worker_jvm_options }}",
        when: deploy_functions_worker is defined and deploy_functions_worker == 'dedicated' }

# Restart brokers, one by one
- hosts: broker
  any_errors_fatal: true
  become: "{{ sudo_needed }}"
  become_method: sudo
  serial: 1
  vars:
    srvStarted: true
    srv_component: 'broker'
    srv_ports: [
        "{% if enable_brkr_tls is defined and enable_brkr_tls|bool %}{{ web_svc_port_tls }}{% else %}{{ web_svc_port }}{% endif %}",
        "{% if enable_brkr_tls is defined and enable_brkr_tls|bool %}{{ broker_svc_port_tls }}{% else %}{{ broker_svc_port }}{% endif %}"
      ]
  roles:
    # Check the current status of brokers
    - { role: misc/_check_svc_status }
    # Stop brokers
    - { role: pulsar/common/pulsar_stopSvc }
    # Start brokers
    - { role: pulsar/common/pulsar_startSvc, srvStarted: false, srv_options: "{{ broker_jvm_options }}" }

# Restart bookies, one by one
- hosts: bookkeeper
  any_errors_fatal: true
  become: "{{ sudo_needed }}"
  become_method: sudo
  # serial: 1
  vars:
    srvStarted: true
    srv_component: 'bookie'
    srv_ports: ["{{ bookie_listening_port }}"]
  roles:
    # Check the current status of bookies
    - { role: misc/_check_svc_status }
    # Stop bookies
    - { role: pulsar/common/pulsar_stopSvc  }
    # Start bookies
    - { role: pulsar/common/pulsar_startSvc, srvStarted: false, srv_options: "{{ bookie_jvm_options }}" }


# Restart zookeepers 
- hosts: zookeeper
  any_errors_fatal: true
  become: "{{ sudo_needed }}"
  become_method: sudo
  serial: 1
  vars:
    srvStarted: true
    srv_component: 'zookeeper'
    srv_ports: ["{{ zk_clnt_port }}"]
  roles:
    # Check the current status of zookeepers
    - { role: misc/_check_svc_status }
    # Stop zookeepers
    - { role: pulsar/common/pulsar_stopSvc }
    # Start zookeepers
    - { role: pulsar/common/pulsar_startSvc, srvStarted: false, srv_options: "{{ zk_jvm_options }}" }

