---
# Stop and clean up AdminConsole application sever
- hosts: adminConsole
  any_errors_fatal: true
  become: "{{ sudo_needed }}"
  become_method: sudo
  vars:
    srvStarted: true
    srv_component: 'adminConsole'
    srv_ports: ["{{ ac_listen_port }}"]
  roles:
    # Check the current status of the AdminConsole application server
    - { role: misc/_check_svc_status }
    # Stop the AdminConsole application server
    - { role: adminconsole/ac_stopAcSvc }
  post_tasks:
    - name: If requested, clean-up AdminConsole binary and log files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ tgt_adminConsole_inst_dir }}"
        - "{{ tgt_adminConsole_sec_dir }}"
        # - "{{ tgt_pkg_adminConsole_dir }}"
      when: purge_adminConsole is defined and purge_adminConsole|bool

