---
- hosts: functions_worker
  any_errors_fatal: true
  become: "{{ sudo_needed }}"
  become_method: sudo
  vars:
    srvStarted: true
    srv_component: 'functions_worker'
    srv_ports: [
      "{% if enable_fwrkr_tls|bool %}{{ funcs_worker_port_tls }}{% else %}{{ funcs_worker_port }}{% endif %}"
    ]
  roles:
    # Check the current status of function workers
    - { role: misc/_check_svc_status }
    # Stop function workers
    - { role: pulsar/common/pulsar_stopSvc }
  post_tasks:
    # Clean up pulsar binaries and logs
    - name: If requested, clean-up pulsar binaries and logs
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ tgt_pulsar_inst_dir }}"
        - "{{ tgt_pulsar_log_homedir }}/functions_worker"
        # - "{{ tgt_pkg_dir }}"
      when: purge_pulsar is defined and purge_pulsar|bool
