---
# Start Zookeeper servers
- hosts: zookeeper
  any_errors_fatal: true
  become: true
  become_method: sudo
  roles: 
    - { role: pulsar/zookeeper/zkpr_startSvc }

# Start Bookkeeper nodes, one by one
- hosts: bookkeeper
  any_errors_fatal: false
  become: true
  become_method: sudo
  roles: 
    - { role: pulsar/bookie/bkie_startSvc }

# - Sanity test of whether bookies are up and running properly
- hosts: bookkeeper
  run_once: true
  roles:
    - { role: pulsar/bookie/bkie_sanityCheck }

# Start Pulsar broker nodes, one by one
- hosts: broker
  any_errors_fatal: true
  become: true
  become_method: sudo
  serial: 1
  roles: 
    - { role: pulsar/broker/brkr_startSvc }