---
# - Start the AdminConsole node.js server
- hosts: adminConsole
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true
  vars:
    srvStarted: true
  roles: 
    # Check the current status of the AdminConsole application server
    - { role: misc/_check_svc_status, 
        srv_component: 'adminConsole', 
        srv_ports: ["{{ ac_listen_port }}"] }
    # Start AdminConsole application server
    - { role: adminconsole/ac_startAcSvc }

# - Start the Nginx server
- hosts: adminConsole
  become: true
  become_method: sudo
  any_errors_fatal: true
  gather_facts: true
  vars:
    srvStarted: true
  roles:
    # Check the current status of the Nginx server
    - { role: misc/_check_svc_status, 
        srv_component: 'nginx', 
        srv_ports: ["{{ nginx_listen_port }}"] }
    # Start the Nginx server
    - { role: adminconsole/ac_startNginxSvc }