###
# this is the playbook that is used to start a pulsar instance that has 2 clusters
###
---
# Start global zookeeper servers, one by one
- hosts: global_zk
  any_errors_fatal: true
  become: true
  become_method: sudo
  serial: 1
  roles: 
    - { role: start_svc_zookeeper_global }

# Start Zookeeper servers, one by one
- hosts: cluster_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  serial: 1
  roles: 
    - { role: start_svc_zookeeper, when: srv_type|regex_search('zk') }

# Start Bookkeeper nodes, one by one
- hosts: cluster_srv
  any_errors_fatal: false
  become: true
  become_method: sudo
  serial: 1
  roles: 
    - { role: start_svc_bookie, when: srv_type|regex_search('bookie') }

# Test whether bookie functions properly after they're up and running
- hosts: cluster_srv
  any_errors_fatal: false
  become: true
  become_method: sudo
  run_once: true
  roles:
    - { role: bookie_sanity_check }

# Start Pulsar broker nodes, one by one
- hosts: cluster_srv
  any_errors_fatal: true
  become: true
  become_method: sudo
  serial: 1
  roles: 
    - { role: start_svc_broker, when: srv_type|regex_search('broker') }