---
# HeartBeat base configuration (non-security)
- include_role:
    name: heartbeat/hb_config/_base

# HeartBeat security related configuration
- include_role:
    name: heartbeat/hb_config/_security
  vars:
    hb_https_cert_file: "{{ tgt_heartBeat_sec_dir }}/tls/server/heartBeat.{{ (hostvars[groups['heartBeat'][0]]['private_ip'])|trim|replace('.','-') }}.crt.pem"
    hb_https_key_file: "{{ tgt_heartBeat_sec_dir }}/tls/server/heartBeat.{{ (hostvars[groups['heartBeat'][0]]['private_ip'])|trim|replace('.','-') }}.key-pk8.pem"
    hb_https_public_ca_file: "{{ tgt_heartBeat_sec_dir }}/tls/rootca/{{ public_cacert_name }}"
  when: enable_hb_security is defined and enable_hb_security|bool
