---
- name: Check if bookkeeper server is already running
  stat:
    path: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-bookie.pid"
  register: stat_result

- name: Start bookeeper server (with default JVM setting), if it is not running yet
  become: true
  become_method: sudo
  become_user: "{{ pulsar_user }}"
  shell: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-daemon start bookie"
  when: not stat_result.stat.exists and (customize_jvm is not defined or not customize_jvm|bool) 

- name: Start bookeeper server, if it is not running yet
  become: true
  become_method: sudo
  become_user: "{{ pulsar_user }}"
  shell: "{{ bookie_jvm_options|trim }} {{ tgt_pulsar_inst_dir }}/bin/pulsar-daemon start bookie"
  when: not stat_result.stat.exists and (customize_jvm is defined and customize_jvm|bool)

- name: Wait until bookkeeper listeneing port {{ bookie_listening_port }} is ready
  wait_for:
    host: "{{ private_ip }}"
    port: "{{ bookie_listening_port }}"
    delay: 2
    timeout: 120