---
- name: Kill the process IDs 
  shell: "{% if sudo_needed|bool %}sudo -u {{ pulsar_user }} {% endif %}kill {% if force_kill is defined and force_kill|bool %}-9{% else %}-TERM{% endif %} {{ srv_pid_num }}"
  when: srv_pid_num is defined