---
- name: Kill the process IDs 
  shell: "{% if sudo_needed|bool %}sudo -u {{ pulsar_user }} {% endif %}kill {% if force_kill is defined and force_kill|bool %}-9{% else %}-TERM{% endif %} {{ srv_pid_num }}"
  when: srv_pid_num is defined

# - name: Get the process IDs of the specified server process
#   shell: "pgrep {{ srv_process_name }}"
#   ignore_errors: yes
#   register: pids_of_server
# - debug: msg="pids_of_server - {{ pids_of_server }}"
#   when: show_debug_msg|bool

# - name: Kill the process IDs 
#   shell: "kill -TERM {{ item }}"
#   # debug: msg="kill -TERM {{ item }}"
#   with_items:
#     - "{{ pids_of_server['stdout_lines'] }}"
#   ignore_errors: yes
#   when: not pids_of_server['failed'] and pids_of_server['stdout_lines']|length > 0