---
# Ubuntu/APT installation
- name: Get the current Nginx server version if it is already installed
  shell: "nginx -version 2>&1"
  ignore_errors: yes
  register: "_nginx_ver"
- debug: msg="_nginx_ver - {{ _nginx_ver }}"
  when: show_debug_msg|bool

- name: Check whether or not we need to install a newer version Nginx
  set_fact:
    install_nginx: "{{ force_nginx_install|bool or _nginx_ver.rc|int != 0 or _nginx_ver.stdout.split('nginx/')[1] is version(tgt_nginx_ver, '<') }}"
- debug: msg="install_nginx - {{ install_nginx }}"
  when: show_debug_msg|bool

- name: Add Nginx APT key
  apt_key:
    # keyserver: keyserver.ubuntu.com
    url: http://nginx.org/keys/nginx_signing.key
    state: present
  when: install_nginx|bool

- name: Add Nginx repository
  apt_repository:
    repo: "deb https://nginx.org/packages/{{ ansible_distribution|lower }}/ {{ ansible_distribution_release|lower }} nginx"
    state: present
  when: install_nginx|bool

- name: Install Nginx server
  apt: 
    #- install a specfic version
    name: nginx={{ tgt_nginx_ver }}-1~{{ ansible_distribution_release|lower }}
    #- install the latest version
    # name: nginx
    update_cache: yes
    state: present
  when: install_nginx|bool

# - name: Change Nginx folder ownership
#   file:
#     path: "{{ item }}"
#     owner: "{{ pulsar_user }}"
#     group: "{{ pulsar_user_group }}"
#     recurse: yes
#   with_items:
#     - /etc/nginx
#     - /usr/lib/nginx