---
- name: If needed, stop the Nginx server using systemd service script
  service:
    name: nginx
    state: stopped
  when: srvStarted|trim|bool and (systemd_nginx_svc is defined and systemd_nginx_svc|bool)

- name: Otherwise, kill the Nginx server process(es)
  include_role:
    role: misc/_kill_svc_pids
  vars:
    srv_process_name: "nginx"
  when: srvStarted|trim|bool and not (systemd_nginx_svc is defined and systemd_nginx_svc|bool)

- name: Wait until Nginx server is gone
  wait_for:
    host: "{{ private_ip }}"
    port: "{{ nginx_listen_port }}"
    state: stopped
    delay: 2
    timeout: 120
  when: srvStarted|trim|bool