---
##
# For each cluster, get a string for all pulsar borker nodes with web service listening ports, e.g.
#   <broker_node_1>:8080,<broker_node_2>:8080,<broker_node_3>:8080
- name: Get "webSvcListStr" (IP:Port:Port) list into a (dictionary) variable
  set_fact: 
    webSvcListStr: |
      {% set webSvcList = [] %}
      {% for node in groups['broker'] %}
      {%   set ignored = webSvcList.append(hostvars[node].private_ip ~ ':' ~ web_svc_port) %}
      {% endfor %}
      {{ webSvcList|join(',') }}
- debug: msg="webSvcListStr - {{ webSvcListStr|trim }}"
  when: show_debug_msg|bool


##
# For each cluster, get a string for all pulsar borker nodes with web service TLS listening ports, e.g.
#   <broker_node_1>:8443,<broker_node_2>:8443,<broker_node_3>:8443
- name: Get "webSvcTlsListStr" (IP:Port:Port) list into a (dictionary) variable
  set_fact: 
    webSvcTlsListStr: |
      {% set webSvcTlsList = [] %}
      {% for node in groups['broker'] %}
      {%   set ignored = webSvcTlsList.append(hostvars[node].private_ip ~ ':' ~ web_svc_port_tls) %}
      {% endfor %}
      {{ webSvcTlsList|join(',') }}
- debug: msg="webSvcTlsListStr - {{ webSvcTlsListStr|trim }}"
  when: show_debug_msg|bool 

##
# For each cluster, get a string for all pulsar borker nodes with broker service listening ports, e.g.
#   <broker_node_1>:6650,<broker_node_2>:6650,<broker_node_3>:6650
- name: Get "brokerSvcListStr" (IP:Port:Port) list into a (dictionary) variable
  set_fact: 
    brokerSvcListStr: |
      {% set brokerSvcList = [] %}
      {% for node in groups['broker'] %}
      {%   set ignored = brokerSvcList.append(hostvars[node].private_ip ~ ':' ~ broker_svc_port) %}
      {% endfor %}
      {{ brokerSvcList|join(',') }}
- debug: msg="brokerSvcListStr - {{ brokerSvcListStr|trim }}"
  when: show_debug_msg|bool


##
# For each cluster, get a string for all pulsar borker nodes with broker service TLS listening ports, e.g.
#   <broker_node_1>:6551,<broker_node_2>:6551,<broker_node_3>:6551
- name: Get "brokerSvcTlsListStr" (IP:Port:Port) list into a (dictionary) variable
  set_fact: 
    brokerSvcTlsListStr: |
      {% set brokerSvcTlsList = [] %}
      {% for node in groups['broker'] %}
      {%   set ignored = brokerSvcTlsList.append(hostvars[node].private_ip ~ ':' ~ broker_svc_port_tls) %}
      {% endfor %}
      {{ brokerSvcTlsList|join(',') }}
- debug: msg="brokerSvcTlsListStr - {{ brokerSvcTlsListStr|trim }}"
  when: show_debug_msg|bool