---
##
# For each cluster, get broker node list with web service port (needed by AdminConsole Niginx)
#   server <broker_node_1>:8080
#   server <broker_node_2>:8080
#   server <broker_node_3>:8080
- name: Get broker web Nginx configuration list (server <broker_ip>:<web_port>;) into a variable
  set_fact: 
    brkrWebArrStrVar: |
      {% set webSvcList = [] %}
      {% for node in groups['broker'] %}
      {%   set ignored = webSvcList.append('    server ' ~ hostvars[node].private_ip ~ ':' ~ web_svc_port ~ ';') %}
      {% endfor %}
      {{ webSvcList|join('\n') }}
- debug: msg="brkrWebArrStrVar - {{ brkrWebArrStrVar }}"
  when: show_debug_msg|bool 

##
# For each cluster, get broker node list with web service TLS port (needed by AdminConsole Niginx)
#   server <broker_node_1>:8443
#   server <broker_node_2>:843
#   server <broker_node_3>:8443
- name: Set broker web TLS Nginx configuration list (server <broker_ip>:<web_tls_port>;) into a variable
  set_fact: 
    brkrWebTLSArrStrVar: |
      {% set webSvcTlsList = [] %}
      {% for node in groups['broker'] %}
      {%   set ignored = webSvcTlsList.append('    server ' ~ hostvars[node].private_ip ~ ':' ~ web_svc_port_tls ~ ';') %}
      {% endfor %}
      {{ webSvcTlsList|join('\n') }}
- debug: msg="brkrWebTLSArrStrVar - {{ brkrWebTLSArrStrVar }}"
  when: show_debug_msg|bool 