---
- name: Create the specified Pulsar user group
  group: 
    name: "{{ pulsar_user_group }}"
    system: yes
    state: present

- name: Create the specified Pulsar user
  user: 
    name: "{{ pulsar_user }}"
    create_home: false
    system: yes
    group: "{{ pulsar_user_group }}"
    state: present

# This makes it easier to run Pulsar CLI commands under the current SSH user
- name: If needed and for convenience, add SSH user into group {{ pulsar_user }}
  user:
    name: "{{ ansible_ssh_user }}"
    groups: "{{ pulsar_user }}"
    append: yes
  when: ssh_user_in_pulsar_group|bool

- name: Create relevant AdminConsole folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    mode: "{{ file_permission_mode }}"
    recurse: yes
  with_items:
    - "{{ tgt_pkg_adminConsole_dir }}"
    - "{{ tgt_adminConsole_inst_dir }}"

- name: Check if AdminConsole binary already exists
  stat:
    path: "{{ tgt_pkg_adminConsole_dir }}/{{ adminConsole_bin_name }}"
  register: adminConsole_distro_stat
- debug: msg={{ adminConsole_distro_stat.stat }}
  when: show_debug_msg|bool

- name: If AdminConsole doesn't exist on the target host yet, copy it from local host when {{ internet_download }} is 'false'
  copy:
    src: "{{ local_bin_homedir }}/{{ adminConsole_bin_name }}"
    dest: "{{ tgt_pkg_adminConsole_dir }}/{{ adminConsole_bin_name }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
  when: not adminConsole_distro_stat.stat.exists and not internet_download|bool

- name: If AdminConsole doesn't exist on the target host yet, download it from internet when {{ internet_download }} is 'true' 
  get_url:
    url: "{{ adminConsole_download_url }}"
    dest: "{{ tgt_pkg_adminConsole_dir }}/{{ adminConsole_bin_name }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
  when: not adminConsole_distro_stat.stat.exists and internet_download|bool

- name: Extract AdminConsole binary release to the target directory
  unarchive:
    src: "{{ tgt_pkg_adminConsole_dir }}/{{ adminConsole_bin_name }}"
    remote_src: yes
    dest: "{{ tgt_adminConsole_inst_dir }}"
    extra_opts: [--strip-components=1]
    keep_newer: yes
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"


- name: If broker authN is enabled, create JWT token related security folders on AdminConsole host
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    mode: "{{ file_permission_mode }}"
    recurse: yes
  with_items:
    - "{{ tgt_adminConsole_sec_dir }}/jwt/token"
  when: enable_brkr_authNR is defined and enable_brkr_authNR|bool

- name: If broker authN is enabled, copy JWT token file from localhost to Pulsar client hosts
  copy:
    src: "{{ item.src_file }}/"
    dest: "{{ item.dest_file }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    force: "{{ force_existing_remote_jwt_token }}"
  with_items:
    - { src_file: "{{ local_jwt_src_homedir }}/token/{{ super_user_roles[0] }}.jwt", 
        dest_file: "{{ tgt_adminConsole_sec_dir }}/jwt/token/{{ super_user_roles[0] }}.jwt" }
  when: enable_brkr_authNR is defined and enable_brkr_authNR|bool

- name: If broker broker TLS is enabled, create TLS certificate related security folders on Pulsar client hosts
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    mode: "{{ file_permission_mode }}"
    recurse: yes
  with_items:
    - "{{ tgt_adminConsole_sec_dir }}/tls/rootca"
  when: enable_brkr_authNR is defined and enable_brkr_authNR|bool

- name: If TLS is enabled, copy the trusted TLS certificate to Pulsar client hosts
  copy:
    src: "{{ item.src_file }}/"
    dest: "{{ item.dest_file }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    force: "{{ force_existing_remote_tls_certs }}"
  with_items:
    - { src_file: "{{ local_tls_src_homedir }}/certs/{{ public_cacert_name }}", 
        dest_file: "{{ tgt_adminConsole_sec_dir }}/tls/rootca/{{ public_cacert_name }}" }
  when: enable_brkr_tls is defined and enable_brkr_tls|bool