###
# Copyright DataStax, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###


---
- name: Initalize cluster metadata
  shell: |
    {% if sudo_needed|bool %}sudo -u {{ pulsar_user }} {% endif %}{{ srv_options|trim }} {{ tgt_pulsar_inst_dir }}/bin/pulsar initialize-cluster-metadata \
    --cluster {{ cluster_name }} \
    --zookeeper {{ hostvars[groups['zookeeper'][0]]['zkListStrVar']|trim }} \
    --configuration-store {{ hostvars[groups['zookeeper'][0]]['zkListStrVar']|trim }} \
    --web-service-url http://{{ hostvars[groups['broker'][0]]['webSvcListStr']|trim }} \
    --broker-service-url pulsar://{{ hostvars[groups['broker'][0]]['brokerSvcListStr']|trim }} \
    --web-service-url-tls https://{{ hostvars[groups['broker'][0]]['webSvcTlsListStr']|trim }} \
    --broker-service-url-tls pulsar+ssl://{{ hostvars[groups['broker'][0]]['brokerSvcTlsListStr']|trim }}
  register: zk_init_cluster_meta_cmdcat
- debug: msg="zk_init_cluster_meta_cmdcat.failed - {{ zk_init_cluster_meta_cmdcat.failed }}"
  when: show_debug_msg|bool 