---
- name: Start AdminConsole if it is not running yet
  become: true
  become_method: sudo
  ## NOTE: Do NOT use Ansible "become_user"! Otherwise, ansible will fail to write .async file under /home/{{ pulsar_user }}
  # become_user: "{{ pulsar_user }}"
  shell: "cd {{ tgt_adminConsole_inst_dir }}/server/; nohup sudo -u {{ pulsar_user }} npm start 2>&1 &"
  # Async shell execution with a very large number
  async: 3153600000 # 100 years
  register: ac_startSvc_cmdcat
  when: not srvStarted|trim|bool
- debug: msg="ac_startSvc_cmdcat - {{ ac_startSvc_cmdcat }}"
  when: show_debug_msg|bool 