---
# Broker base configuration (non-security)
- include_role:
    name: pulsar/broker/brkr_config/_base

# Broker version 2.10 specific configuration
- include_role:
    name: pulsar/broker/brkr_config/_ver2.10

# Broker security related configuration
- include_role:
    name: pulsar/broker/brkr_config/_security