---
# Get the bookie node count which is requrired to configure message replication settings
- name: Set bookie node count into a variable
  set_fact: 
    bookieCnt: |
      {% set count = [0] %}
      {% for node in groups['bookkeeper'] %}
      {%   if count.append(count.pop() + 1) %}{% endif %}
      {% endfor %}
      {{ count.pop() }}
- debug: msg="bookieCnt - {{ bookieCnt }}"
  when: show_debug_msg|bool

# Get the bookie rack count which is required to calculate rack-awareness settings
- name: Set the bookie rack count into a variable
  set_fact:
    bookieRackCnt: |
      {% set rack_list = [] %}
      {% set count = [0] %}
      {% for node in groups['bookkeeper'] if hostvars[node].rack_name not in rack_list %}
      {%   set ignored = rack_list.append(hostvars[node].rack_name) %}
      {%   if count.append(count.pop() + 1) %}{% endif %}
      {% endfor %}
      {# {{ rack_list|unique|count }} #}
      {{ count.pop() }}
- debug: msg="bookieRackCnt - {{ bookieRackCnt }}"
  when: show_debug_msg|bool


- name: Set ensemble size, write, and ack quorum count
  set_fact:
    ensemble_size: "{% if force_message_rf_setting is defined and force_message_rf_setting|bool %}{{ cust_ensemble_size }}{% elif bookieCnt|int >= 3 %}3{% else %}{{ bookieCnt|int }}{% endif %}"
    write_quorum_cnt: "{% if force_message_rf_setting is defined and force_message_rf_setting|bool %}{{ cust_write_quorum }}{% elif bookieCnt|int >= 3 %}3{% else %}{{ bookieCnt|int }}{% endif %}"
    ack_quorum_cnt: "{% if force_message_rf_setting is defined and force_message_rf_setting|bool %}{{ cust_ack_quorum }}{% elif bookieCnt|int >= 3 %}2{% else %}1{% endif %}"
- debug: msg="ensemble_size={{ ensemble_size }}, write_quorum_cnt={{ write_quorum_cnt }}, ack_quorum_cnt={{ ack_quorum_cnt }}"
  when: show_debug_msg|bool

- name: Modify Pulsar broker config file for general, non-security related settings
  lineinfile:
    path: "{{ broker_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^zookeeperServers=', line: "zookeeperServers={{ hostvars[groups['zookeeper'][0]]['zkListStrVar']|trim }}" }
    - { regexp: '^configurationStoreServers=', line: "configurationStoreServers={{ hostvars[groups['zookeeper'][0]]['zkListStrVar']|trim }}" }
    - { regexp: '^clusterName=', line: 'clusterName={{ cluster_name }}' }
    - { regexp: '^brokerServicePort=', line: 'brokerServicePort={{ broker_svc_port }}' }
    - { regexp: '^webServicePort=', line: 'webServicePort={{ web_svc_port }}' }
    - { regexp: '^managedLedgerDefaultEnsembleSize=', line: 'managedLedgerDefaultEnsembleSize={{ ensemble_size }}'}
    - { regexp: '^managedLedgerDefaultWriteQuorum=', line: 'managedLedgerDefaultWriteQuorum={{ write_quorum_cnt }}' }
    - { regexp: '^managedLedgerDefaultAckQuorum=', line: 'managedLedgerDefaultAckQuorum={{ ack_quorum_cnt }}' }
    - { regexp: '^forceDeleteTenantAllowed=', line: 'forceDeleteTenantAllowed={{ forceDeleteTenantAllowed }}' }
    - { regexp: '^forceDeleteNamespaceAllowed=', line: 'forceDeleteNamespaceAllowed={{ forceDeleteNamespaceAllowed }}' }
    - { regexp: '^brokerDeleteInactiveTopicsEnabled=', line: 'brokerDeleteInactiveTopicsEnabled={{ brokerDeleteInactiveTopicsEnabled }}' }
    - { regexp: '^topicFencingTimeoutSeconds=', line: 'topicFencingTimeoutSeconds={{ topicFencingTimeoutSeconds }}' }
    #### 
    ## - Enable function worker as part of the broker (not recommended for PROD environment)
    ##   NOTE/TBD: improve dedicated function worker deployment!
    # - { regexp: '^functionsWorkerEnabled=', line: 'functionsWorkerEnabled=true' }

- name: Modify Pulsar broker config file for rack-awareness related settings
  lineinfile:
    path: "{{ broker_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^bookkeeperClientRackawarePolicyEnabled=', 
        line: 'bookkeeperClientRackawarePolicyEnabled=true' }
    - { regexp: '^bookkeeperClientMinNumRacksPerWriteQuorum=', 
        line: 'bookkeeperClientMinNumRacksPerWriteQuorum={% if bookieRackCnt|int < 2 %}1{% elif minNumRackPerWQ|int > bookieRackCnt|int %}{{ bookieRackCnt|int }}{% else %}{{ minNumRackPerWQ|int }}{% endif %}' }
    - { regexp: '^bookkeeperClientEnforceMinNumRacksPerWriteQuorum=', 
        line: 'bookkeeperClientEnforceMinNumRacksPerWriteQuorum={{ enforceMinNumRackPerWQ }}' }
  when: config_rackAwareness is defined and config_rackAwareness|bool