---
- name: Check the existing Pulsar version
  shell: |
    {% if sudo_needed|bool %}sudo -u {{ pulsar_user }} {% endif %}{{ srv_options|trim }} {{ tgt_pulsar_inst_dir }}/bin/pulsar version
  register: pulsar_ver_output

- name: Set existing Pulsar version in a variable  
  set_fact:
    cur_pulsar_ver: "{{ pulsar_ver_output.stdout_lines[0] | split(':') | last | trim }}"

- debug: msg="cur_pulsar_ver - {{ cur_pulsar_ver }}"
  when: show_debug_msg|bool