---
- name: Copy Pulsar HeartBeat runtime config (runtime.yaml) template
  template:
    src: templates/hb_runtime.yaml.tmp
    dest: "{{ tgt_heartBeat_inst_dir }}/runtime.yaml"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    mode: "{{ file_permission_mode_noexec }}"

- name: Replace Pulsar HeartBeat config setting placeholders with cluster specific information
  vars:
    broker_websvc_url: "{% if enable_brkr_tls is defined and enable_brkr_tls|bool %}https://{{ hostvars[groups['broker'][0]]['webSvcTlsListStr']|trim }}{% else %}http://{{ hostvars[groups['broker'][0]]['webSvcListStr']|trim }}{% endif %}"
    broker_pulsarvc_url: "{% if enable_brkr_tls is defined and enable_brkr_tls|bool %}pulsar+ssl://{{ hostvars[groups['broker'][0]]['brokerSvcTlsListStr']|trim }}{% else %}pulsar://{{ hostvars[groups['broker'][0]]['brokerSvcListStr']|trim }}{% endif %}"
  replace:
       path: "{{ tgt_heartBeat_inst_dir }}/runtime.yaml"
       regexp: "{{ item.regexp }}"
       replace: "{{ item.line }}"
  with_items:
     - { regexp: '<<home_cluster>>', line: "{{ cluster_name }}" }
     - { regexp: '<<broker_WebSvc_List_Str>>', line: "{{ broker_websvc_url.split(',')[0] }}" }     
     - { regexp: '<<broker_Svc_List_Str>>', line: "{{ broker_pulsarvc_url }}" }
     - { regexp: '<<hb_Listen_Port>>', line: "{{ hb_listen_port }}" }