---
#########################
# Common broker configuration settings
# that are applicable to both to the following versions:
# - 2.8(.*)
# - 2.10(.*)
# -----------------------
- name: Modify Pulsar broker config file for mandatory settings
  lineinfile:
    path: "{{ broker_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^zookeeperServers=", line: "zookeeperServers={{ hostvars[groups['zookeeper'][0]]['zkListStrVar']|trim }}" }
    - { regexp: "^configurationStoreServers=", line: "configurationStoreServers={{ hostvars[groups['zookeeper'][0]]['zkListStrVar']|trim }}" }
    - { regexp: "^clusterName=", line: "clusterName={{ cluster_name }}" }
    - { regexp: "^brokerServicePort=", line: "brokerServicePort={{ broker_svc_port }}" }
    - { regexp: "^webServicePort=", line: "webServicePort={{ web_svc_port }}" }
    - { regexp: "^managedLedgerDefaultEnsembleSize=", line: "managedLedgerDefaultEnsembleSize={{ ensemble_size|trim }}"}
    - { regexp: "^managedLedgerDefaultWriteQuorum=", line: "managedLedgerDefaultWriteQuorum={{ write_quorum_cnt|trim }}" }
    - { regexp: "^managedLedgerDefaultAckQuorum=", line: "managedLedgerDefaultAckQuorum={{ ack_quorum_cnt|trim }}" }
    - { regexp: "^transactionCoordinatorEnabled=", line: "transactionCoordinatorEnabled={{ enable_transaction }}" }
    - { regexp: "^systemTopicEnabled=", line: "systemTopicEnabled=true" }

- name: Modify Pulsar broker config file to enable shared functions worker
  lineinfile:
    path: "{{ broker_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:    
    # NOTE: Function workers can be started as part of brokres. However, 
    # 1) This is only recommended for DEV purpose.
    # 2) For PROD and/or PERF TESTING environment, it is always recommended to deploy dedicated function workers
    - { regexp: "^functionsWorkerEnabled=", line: "functionsWorkerEnabled=true" }
  when: deploy_functions_worker is defined and deploy_functions_worker == 'shared'

- name: Modify Pulsar broker config file for rack-awareness related settings
  lineinfile:
    path: "{{ broker_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^bookkeeperClientRackawarePolicyEnabled=", 
        line: "bookkeeperClientRackawarePolicyEnabled=true" }
    - { regexp: "^bookkeeperClientMinNumRacksPerWriteQuorum=", 
        line: "bookkeeperClientMinNumRacksPerWriteQuorum={{ minNumRackPerWQ }}" }
    - { regexp: "^bookkeeperClientEnforceMinNumRacksPerWriteQuorum=", 
        line: "bookkeeperClientEnforceMinNumRacksPerWriteQuorum={{ enforceMinNumRackPerWQ|lower }}" }
  when: config_rackAwareness is defined and config_rackAwareness|bool

- name: Modify Pulsar broker config file for misc settings
  lineinfile:
    path: "{{ broker_conf_file }}"
    regexp: "^(#\\s?)?{{ item.key }}="
    line: "{{ item.key }}={{ item.value }}"
  with_items:
    - "{{ lookup('dict', misc_broker_config_dict) }}"