---
#########################
# Create broker security related folders for client connection on Pulsar client hosts
# ------------------------
- name: If broker authN is enabled, create JWT token related security folders on Pulsar client hosts
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    mode: "{{ file_permission_mode }}"
    recurse: yes
  with_items:
    - "{{ tgt_pulsar_sec_dir }}/jwt/token"
  when: enable_brkr_authNZ is defined and enable_brkr_authNZ|bool

- name: If broker TLS is enabled, create TLS certificate related security folders on Pulsar client hosts
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    mode: "{{ file_permission_mode }}"
    recurse: yes
  with_items:
    - "{{ tgt_pulsar_sec_dir }}/tls/rootca"
  when: enable_brkr_tls is defined and enable_brkr_tls|bool


#########################
# Copy locally generated broker security files to Pulsar client hosts
# ------------------------
- name: If broker authN is enabled, copy JWT token file to Pulsar client hosts
  copy:
    src: "{{ item.src_file }}/"
    dest: "{{ item.dest_file }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    force: "{{ force_tgt_jwt_token }}"
  with_items:
    - { src_file: "{{ local_jwt_src_homedir }}/token/brokers/{{ brkr_super_user_roles[0] }}.jwt", 
        dest_file: "{{ tgt_jwt_dest_homedir }}/token/{{ brkr_super_user_roles[0] }}.jwt" }
  when: enable_brkr_authNZ is defined and enable_brkr_authNZ|bool

- name: If TLS is enabled, copy the trusted TLS certificate to Pulsar client hosts
  copy:
    src: "{{ item.src_file }}/"
    dest: "{{ item.dest_file }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    force: "{{ force_tgt_tls_certs }}"
  with_items:
    - { src_file: "{{ local_tls_src_homedir }}/certs/{{ public_cacert_name }}", 
        dest_file: "{{ tgt_tls_dest_homedir }}/rootca/{{ public_cacert_name }}" }
  when: enable_brkr_tls is defined and enable_brkr_tls|bool


#########################
# Configure security related settings in client.conf
# ------------------------
- name: Modify Pulsar client configuration file - set web service and broker service URLs
  lineinfile:
    path: "{{ pulsar_client_config_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    # Broker authN/authR related settings
    - { regexp: "^authPlugin=", 
        line: "authPlugin={% if enable_brkr_authNZ is defined and enable_brkr_authNZ|bool %}org.apache.pulsar.client.impl.auth.AuthenticationToken{% else %} {% endif %}" }
    - { regexp: "^authParams=", 
        line: "authParams={% if enable_brkr_authNZ is defined and enable_brkr_authNZ|bool %}file://{{ tgt_jwt_dest_homedir }}/token/{{ brkr_super_user_roles[0] }}.jwt{% else %} {% endif %}" }
    # Broker TLS encryption related settings
    - { regexp: "^webServiceUrl=", 
        line: "webServiceUrl={% if enable_brkr_tls is defined and enable_brkr_tls|bool %}https://{{ hostvars[groups['broker'][0]]['webSvcTlsListStr']|trim }}{% else %}http://{{ hostvars[groups['broker'][0]]['webSvcListStr']|trim }}{% endif %}" }
    - { regexp: "^brokerServiceUrl=", 
        line: "brokerServiceUrl={% if enable_brkr_tls is defined and enable_brkr_tls|bool %}pulsar+ssl://{{ hostvars[groups['broker'][0]]['brokerSvcTlsListStr']|trim }}{% else %}pulsar://{{ hostvars[groups['broker'][0]]['brokerSvcListStr']|trim }}{% endif %}" }
    - { regexp: "^tlsTrustCertsFilePath=", 
        line: "tlsTrustCertsFilePath={% if enable_brkr_tls is defined and enable_brkr_tls|bool %}{{ tgt_tls_dest_homedir }}/rootca/{{ public_cacert_name }}{% else %} {% endif %}" }
    ## Disable Pulsar server host name verification for now
    # - { regexp: "^tlsEnableHostnameVerification=", 
    #     line: "tlsEnableHostnameVerification=true" }
