---
- name: Create bookeeper data folder - "{{ zk_data_dir }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user }}"
  with_items:
    - "{{ bookie_storage_mnt_paths }}"  

#- debug: msg={{ hostvars[groups['cluster_srv'][0]]['zkstrDict'] }}
- name: Modify bookkeeper main config file - {{ bk_conf_file }}
  lineinfile:
    path: "{{ bk_conf_file }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^zkServers=', line: "zkServers={{ zkListStrVar }}" }
    - { regexp: '^bookiePort=', line: 'bookiePort={{ bookie_listening_port }}' }
    - { regexp: '^httpServerPort=', line: 'httpServerPort={{ bk_stats_port }}' }
    - { regexp: '^prometheusStatsHttpPort=', line: 'prometheusStatsHttpPort={{ bk_stats_port }}' }
    - { regexp: '^# journalDirectories=', line: 'journalDirectories={{ bookie_storage_mnt_paths[0]}}' }
    - { regexp: '^ledgerDirectories=', line: 'ledgerDirectories={{ bookie_storage_mnt_paths[1]}}' }    