---
- name: Check if Pulsar's server component ({{ srv_component }}) process ID file already exists
  stat:
    path: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-{{ srv_component }}.pid"
  register: srv_pid_stat
- debug: msg="({{ srv_component }}) srv_pid_stat - {{ srv_pid_stat }}"
  when: show_debug_msg|bool

# this is needed because in Pulsar, the bookkeeper service name is 'bookie', but the configuraiton file name starts with 'bookkeeper'
- set_fact:
    srv_component2: "{% if srv_component == 'booke' %}bookkeeper{% else %}{{ srv_component }}{% endif %}"
- set_fact:
    get_pid_cmd: "ps -ef | grep -v grep | grep pulsar | grep -E \"{{ srv_component2 | replace('_', '-') }}.(conf|yaml)\" | awk '{print $2}'"
- debug: msg="[{{ srv_component2 }}] -- {{ get_pid_cmd }} "
  when: show_debug_msg|bool

- name: Get the actual running server component ({{ srv_component }}) process PID 
  shell: "{% if sudo_needed|bool %}sudo -u {{ pulsar_user }} {% endif %}ps -ef | grep -v grep | grep pulsar | grep -E \"{{ srv_component2 | replace('_', '-') }}.(conf|yaml)\" | awk '{print $2}'"
  register: pids_of_server
- debug: msg="pids_of_server - {{ pids_of_server.stdout_lines }}"
  when: show_debug_msg|bool

#
# Sometimes the Pulsar PID file may disappear while the actual server process is still running 
# - this could be due to a failed server "stop" process
# - if the Pulsar PID file doesn't exit and start the server "stop" process again, it will fail
#
- name: Create the server component ({{ srv_component }}) process ID file if it doesn't exist but the server process is still running
  copy:
    dest: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-{{ srv_component }}.pid"
    content: "{{ item }}"
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
  with_items:
    - "{{ pids_of_server.stdout_lines }}"
  when: |
    srvStarted|trim|bool and not srv_pid_stat.stat.exists and 
    not pids_of_server.failed|bool and pids_of_server.stdout_lines|length > 0

- name: Stop the Pulsar server component ({{ srv_component }}), if it is already running
  # NOTE: replace "functions_worker" to "functions-worker"
  shell: "{% if sudo_needed|bool %}sudo -u {{ pulsar_user }} {% endif %}{{ tgt_pulsar_inst_dir }}/bin/pulsar-daemon stop {{ srv_component | replace('_', '-') }}"
  when: srvStarted|trim|bool

- name: Wait until the Pulsar server component ({{ srv_component }}) is gone
  wait_for:
    host: "{{ private_ip }}"
    port: "{{ item }}"
    state: stopped
    delay: 2
    timeout: 120
  with_items:
    - "{{ srv_ports }}"
  when: srvStarted|trim|bool