---
- name: Stop the Pulsar server component ({{ srv_component }}), if it is already running
  # NOTE: replace "functions_worker" to "functions-worker"
  shell: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-daemon stop {{ srv_component | replace('_', '-') }}"
  when: srvStarted|trim|bool

- name: Wait until the Pulsar server component ({{ srv_component }}) is gone
  wait_for:
    host: "{{ private_ip }}"
    port: "{{ item }}"
    state: stopped
    delay: 2
    timeout: 120
  with_items:
    - "{{ srv_ports }}"
  when: srvStarted|trim|bool

- name: Delete the Pulsar server component ({{ srv_component }}) process ID file
  file:
    path: "{{ tgt_pulsar_inst_dir }}/bin/pulsar-{{ srv_component }}.pid"
    state: absent
  ignore_errors: yes