---
- name: Check if ~/.bash_profile exists
  stat:
    path: ~/.bash_profile
  register: bash_profile_stat
- name: Create ~/.bash_profile if not exists
  file:
    path: ~/.bash_profile
    state: touch
  when: not bash_profile_stat.stat.exists
- name: Add Pulsar executables in $PATH system variable
  lineinfile:
    dest: ~/.bash_profile
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: "^PULSAR_HOME=", line: "PULSAR_HOME={{ tgt_pulsar_inst_dir }}" }
    # No match add the line at EOF
    - { regexp: "NO-MATCH", line: "PATH=\"$PULSAR_HOME/bin:$PATH\"" }