---
## Log for all Pulsar severs
- name: Create local folder (timestamp based) to host server logs
  file:
    path: "{{ local_collected_srvfiles_homedir }}/{{ bkup_subfolder }}/log/{{ srv_component }}/{{ item }}"
    state: directory
  when: |
    (file_types is not defined or 'all' in file_types or 'log' in file_types) and
    (srv_types is not defined or srv_component in srv_types) and 
    (srvhost_ptn is not defined or srvhost_ptn in hostvars[item]['private_ip'])

## Config for all Pulsar servers
- name: Create local folder (timestamp based) to host server configuration
  file:
    path: "{{ local_collected_srvfiles_homedir }}/{{ bkup_subfolder }}/config/{{ srv_component }}/{{ item }}"
    state: directory
  when: |
    (file_types is not defined or 'all' in file_types or 'cfg' in file_types) and
    (srv_types is not defined or srv_component in srv_types) and 
    (srvhost_ptn is not defined or srvhost_ptn in hostvars[item]['private_ip'])

## Thread dump for all Pulsar servers
- name: Create local folder (timestamp based) to host server thread dump
  file:
    path: "{{ local_collected_srvfiles_homedir }}/{{ bkup_subfolder }}/thrdump/{{ srv_component }}/{{ item }}"
    state: directory
  when: |
    (file_types is not defined or 'all' in file_types or 'thrdump' in file_types) and
    (srv_types is not defined or srv_component in srv_types) and 
    (srvhost_ptn is not defined or srvhost_ptn in hostvars[item]['private_ip'])

## Heap dump for all Pulsar servers
#  - must specify "file_types" variable and include "heapdump" as part of it
- name: Create local folder (timestamp based) to host server heap dump
  file:
    path: "{{ local_collected_srvfiles_homedir }}/{{ bkup_subfolder }}/heapdump/{{ srv_component }}/{{ item }}"
    state: directory
  when: |
    file_types is defined and ('all' in file_types or 'heapdump' in file_types) and
    (srv_types is not defined or srv_component in srv_types) and 
    (srvhost_ptn is not defined or srvhost_ptn in hostvars[item]['private_ip'])