---
# Bookkeeper base configuration (non-security)
- include_role:
    name: pulsar/autorecovery/ar_config/_base

# Bookkeeper version 2.10 specific configuration
- include_role:
    name: pulsar/autorecovery/ar_config/_ver2.10
  when: pulsarLS_ver_signifant is version('2.10', '>=')