- name: Create the specified Pulsar user group
  group: 
    name: "{{ pulsar_user_group }}"
    system: yes
    state: present

- name: Create the specified Pulsar user
  user: 
    name: "{{ pulsar_user }}"
    create_home: false
    system: yes
    group: "{{ pulsar_user_group }}"
    state: present

# This makes it easier to run Pulsar CLI commands under the current SSH user
- name: If needed and for convenience, add SSH user into group {{ pulsar_user }}
  user:
    name: "{{ ansible_ssh_user }}"
    groups: "{{ pulsar_user_group }}"
    append: yes
  when: ssh_user_in_pulsar_group|bool

- name: Create relevant Pulsar folders
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ pulsar_user }}"
    group: "{{ pulsar_user_group }}"
    mode: "{{ file_permission_mode }}"
    recurse: yes
  with_items:
    - "{{ tgt_pkg_pulsar_dir }}"
    - "{{ tgt_pulsar_inst_dir }}"
    - "{{ tgt_pulsar_log_homedir }}"
    - "{{ tgt_pulsar_gc_log_homedir }}"